trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'rg-deploiement-demo'
  location: 'canadacentral'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'NomConnexionAzure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "=== Déploiement du Storage Account ==="
      az deployment group create \
        --resource-group ${{ variables.resourceGroupName }} \
        --template-file bicep/storage.bicep \
        --parameters storageAccountName=stgimgdemo containerName=input-images location=${{ variables.location }}

      echo "=== Déploiement du Service Bus ==="
      az deployment group create \
        --resource-group ${{ variables.resourceGroupName }} \
        --template-file bicep/servicebus.bicep \
        --parameters serviceBusNamespaceName=imgbusdemo queueName=image-processing-queue location=${{ variables.location }}

      echo "=== Déploiement de la Function App ==="
      az deployment group create \
        --resource-group ${{ variables.resourceGroupName }} \
        --template-file bicep/functionapp.bicep \
        --parameters functionAppName=imgfuncdemo planName=plan-img-fn location=${{ variables.location }}
    displayName: 'Déploiement complet via Bicep'
